create database RestaurantOrderManagementSystem
use RestaurantOrderManagementSystem

CREATE TABLE USER_ (
    UserID INT IDENTITY (101,1) PRIMARY KEY,
    FName VARCHAR(50) NOT NULL,
    MName VARCHAR(50),
    LName VARCHAR(50) NOT NULL,
    CNumber VARCHAR(15) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Uname VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL,
	SecurityKey VARCHAR(15) UNIQUE NOT NULL,
	UStatus VARCHAR(15) NOT NULL,
    ProfilePicture VARBINARY(MAX) NOT NULL,
);

CREATE TABLE CUSTOMER (
    CustomerID INT IDENTITY(1001,1) PRIMARY KEY,
    FName VARCHAR(50) NOT NULL,
    MName VARCHAR(50),
    LName VARCHAR(50) NOT NULL,
    CNumber VARCHAR(15),
);

CREATE TABLE MENUITEMCATEGORY (
    MICatID INT IDENTITY (1,1) PRIMARY KEY,
    CatDes VARCHAR(100) NOT NULL
);

CREATE TABLE ORDER_ (
    OrderID INT IDENTITY (1001,1) PRIMARY KEY,
    UserID INT NOT NULL,
    CustomerID INT NOT NULL,
    OType VARCHAR(50) NOT NULL,
    SAmount DECIMAL(10,2) NOT NULL,
    DateTime DATETIME NOT NULL,
    OStatus VARCHAR(50) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User_(UserID),
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE MENUITEM (
    MenuItemID INT IDENTITY (1,1) PRIMARY KEY,
    MICatID INT NOT NULL,
    MIName VARCHAR(50) NOT NULL,
    UPrice DECIMAL(10,2) NOT NULL,
    NServing INT NOT NULL,
    MIStatus VARCHAR(50) NOT NULL,
	ItemPicture VARBINARY(MAX) NOT NULL,
    FOREIGN KEY (MICatID) REFERENCES MENUITEMCATEGORY(MICatID)
	
);

CREATE TABLE BILL (
    BillID INT IDENTITY (1001,1) PRIMARY KEY,
	OrderID INT UNIQUE,
    DateTime DATETIME NOT NULL,
    VATAmount DECIMAL(10,2) NOT NULL,
	VATSales DECIMAL(10,2) NOT NULL,
    TotalAmount DECIMAL(10,2) NOT NULL,
    BStatus VARCHAR(50) NOT NULL
	FOREIGN KEY (OrderID) REFERENCES ORDER_(OrderID)
);

CREATE TABLE ORDERITEM (
    OrderID INT NOT NULL,
    MenuItemID INT NOT NULL,
    Quantity INT NOT NULL,
    TotalPrice DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (OrderID, MenuItemID),
	FOREIGN KEY (OrderID) REFERENCES ORDER_(OrderID),
    FOREIGN KEY (MenuItemID) REFERENCES MENUITEM(MenuItemID)
);

CREATE TABLE PAYMENT (
    PaymentID INT IDENTITY (1001,1) PRIMARY KEY,
	BillID INT UNIQUE,
    DateTime DATETIME NOT NULL,
	PaymentMode varchar (50),
	FOREIGN KEY (BillID) REFERENCES BILL(BillID)
);

CREATE TABLE CASHPAYMENT (
    C_PaymentID INT PRIMARY KEY IDENTITY (101,1),
	PaymentID INT UNIQUE,
    CashTendered DECIMAL(10,2) NOT NULL,
    Change DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID)
);

CREATE TABLE DISCOUNT (
    DiscountID VARCHAR (255) PRIMARY KEY,
    FName VARCHAR(50) NOT NULL,
    MName VARCHAR(50),
    LName VARCHAR(50) NOT NULL,
    EDate DATE NOT NULL,
    DCategory VARCHAR(50) NOT NULL,
    Mun VARCHAR(50) NOT NULL,
    Prov VARCHAR(50) NOT NULL
);

CREATE TABLE BILLWITHDISCOUNT (
    BillID INT,
    DiscountID VARCHAR(255) NOT NULL,
	LessVAT DECIMAL(10,2) NOT NULL,
	DiscountAmount DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (BillID, DiscountID),
    FOREIGN KEY (DiscountID) REFERENCES DISCOUNT(DiscountID),
	FOREIGN KEY (BillID) REFERENCES BILL(BillID)
);

